name: Hello
on: push
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: |
                git log -1
                tree -a .
            - uses: actions/checkout@v4
              with:
                ref: main